import type { NextPage } from 'next';

import Head from 'next/head';

import styles from '../styles/Home.module.css';

const Home: NextPage = (props) => {
  const { quote } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Test: {JSON.stringify(quote)}</p>;
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  // fetch data
  // create static pages
  const quote = await fetch(
    "https://breaking-bad-quotes.herokuapp.com/v1/quotes"
  ).then((resp) => resp.json());

  return {
    props: {
      quote,
    },
  };
};

export default Home;
